"""
Report generation service — PDF and CSV exports.

Generates monitoring reports for facilities:
    - Monthly summary: TROPOMI + S2 data for a given month
    - Detection report: individual S2 plume detection detail
    - Compliance report: NGER baseline comparison
"""

import csv
import io
import json
import logging
from datetime import date

import psycopg
from psycopg.rows import dict_row

from app.config import get_settings

logger = logging.getLogger(__name__)


def generate_facility_csv(
    facility_id: int,
    start_date: date,
    end_date: date,
    report_type: str = "detections",
) -> bytes:
    """Generate a CSV export of facility monitoring data.

    Args:
        facility_id: Facility ID
        start_date: Report period start
        end_date: Report period end
        report_type: "detections" or "tropomi"

    Returns:
        CSV file as bytes
    """
    settings = get_settings()

    with psycopg.connect(settings.database_url) as conn:
        with conn.cursor(row_factory=dict_row) as cur:
            # Get facility info
            cur.execute(
                "SELECT name, state, operator FROM facilities WHERE id = %s",
                [facility_id],
            )
            facility = cur.fetchone()

            if report_type == "detections":
                cur.execute(
                    """
                    SELECT scene_id, scene_datetime::text,
                           emission_rate_kg_hr, uncertainty_kg_hr,
                           ime_kg, effective_wind_m_s, plume_length_m,
                           plume_area_m2, plume_pixels,
                           wind_speed_10m, wind_direction,
                           confidence, solar_zenith, cloud_cover
                    FROM s2_detections
                    WHERE facility_id = %s
                      AND scene_datetime >= %s
                      AND scene_datetime < %s
                    ORDER BY scene_datetime
                    """,
                    [facility_id, start_date, end_date],
                )
            else:
                cur.execute(
                    """
                    SELECT period_start::text, period_end::text,
                           aggregation_period,
                           mean_enhancement_ppb, max_enhancement_ppb,
                           central_box_mean_ppb, sample_count,
                           valid_pixel_fraction, mean_wind_speed,
                           intensity_score, background_ch4_ppb
                    FROM tropomi_observations
                    WHERE facility_id = %s
                      AND period_start >= %s
                      AND period_end <= %s
                    ORDER BY period_start
                    """,
                    [facility_id, start_date, end_date],
                )

            rows = cur.fetchall()

    if not rows:
        return b""

    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=rows[0].keys())

    # Header comment
    output.write(f"# Facility: {facility['name']} ({facility['state']})\n")
    output.write(f"# Operator: {facility['operator']}\n")
    output.write(f"# Period: {start_date} to {end_date}\n")
    output.write(f"# Report type: {report_type}\n")
    output.write(f"# Generated by: MethLab / GeoSynergy\n")

    writer.writeheader()
    writer.writerows(rows)

    return output.getvalue().encode("utf-8")


def generate_compliance_summary(
    facility_id: int,
    year: int,
) -> dict:
    """Generate NGER compliance summary for a facility.

    Compares observed emissions from S2 detections against the
    NGER baseline to assess Safeguard Mechanism exposure.

    Args:
        facility_id: Facility ID
        year: Reporting year

    Returns:
        Compliance summary dict
    """
    settings = get_settings()

    with psycopg.connect(settings.database_url) as conn:
        with conn.cursor(row_factory=dict_row) as cur:
            # Get facility info + baseline
            cur.execute(
                """
                SELECT name, state, operator, nger_id, nger_baseline,
                       nger_designated, safeguard_covered
                FROM facilities WHERE id = %s
                """,
                [facility_id],
            )
            facility = cur.fetchone()

            # Sum S2 detections for the year
            cur.execute(
                """
                SELECT count(*) as detection_count,
                       avg(emission_rate_kg_hr) as avg_emission_kg_hr,
                       max(emission_rate_kg_hr) as max_emission_kg_hr,
                       sum(emission_rate_kg_hr) as total_flux_kg_hr
                FROM s2_detections
                WHERE facility_id = %s
                  AND scene_datetime >= %s
                  AND scene_datetime < %s
                """,
                [facility_id, f"{year}-01-01", f"{year + 1}-01-01"],
            )
            detections = cur.fetchone()

            # TROPOMI annual intensity
            cur.execute(
                """
                SELECT intensity_score, central_box_mean_ppb, sample_count
                FROM tropomi_observations
                WHERE facility_id = %s
                  AND aggregation_period = 'annual'
                  AND period_start >= %s
                ORDER BY period_start DESC
                LIMIT 1
                """,
                [facility_id, f"{year}-01-01"],
            )
            tropomi = cur.fetchone()

    baseline = facility.get("nger_baseline") if facility else None

    # Rough annual estimate from average detection rate
    # (This is illustrative — real compliance would use continuous monitoring)
    avg_kg_hr = detections.get("avg_emission_kg_hr") or 0 if detections else 0
    estimated_annual_t = avg_kg_hr * 8760 / 1000  # kg/hr * hours/year / 1000

    # Convert CH4 to CO2-equivalent (GWP100 = 28)
    estimated_co2e_t = estimated_annual_t * 28

    compliance_status = "unknown"
    exceedance_pct = None
    if baseline and estimated_co2e_t > 0:
        if estimated_co2e_t > baseline * 1.1:
            compliance_status = "exceeding"
            exceedance_pct = (estimated_co2e_t - baseline) / baseline * 100
        elif estimated_co2e_t > baseline * 0.9:
            compliance_status = "near_baseline"
        else:
            compliance_status = "below_baseline"

    return {
        "facility": facility,
        "year": year,
        "detection_summary": detections,
        "tropomi_summary": tropomi,
        "estimated_annual_ch4_t": estimated_annual_t,
        "estimated_annual_co2e_t": estimated_co2e_t,
        "nger_baseline_co2e_t": baseline,
        "compliance_status": compliance_status,
        "exceedance_pct": exceedance_pct,
    }
